services:
  - type: web
    name: book-api-mongo-jwt
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: CORS_ORIGIN
        value: "*"
